# -*- coding: utf-8 -*-
# Generated by https://github.com/verloop/twirpy/protoc-gen-twirpy.  DO NOT EDIT!
# source: proto/rpc.proto

from google.protobuf import symbol_database as _symbol_database

from twirp.base import Endpoint
from twirp.server import TwirpServer
from twirp.client import TwirpClient

_sym_db = _symbol_database.Default()

class DeathOrTaxesServer(TwirpServer):

	def __init__(self, *args, service, server_path_prefix="/twirp"):
		super().__init__(service=service)
		self._prefix = F"{server_path_prefix}/DeathOrTaxes"
		self._endpoints = {
			"GetCollisionMap": Endpoint(
				service_name="DeathOrTaxes",
				name="GetCollisionMap",
				function=getattr(service, "GetCollisionMap"),
				input=_sym_db.GetSymbol("GetCollisionMapReq"),
				output=_sym_db.GetSymbol("GetCollisionMapResp"),
			),
			"GetUpdates": Endpoint(
				service_name="DeathOrTaxes",
				name="GetUpdates",
				function=getattr(service, "GetUpdates"),
				input=_sym_db.GetSymbol("GetUpdatesReq"),
				output=_sym_db.GetSymbol("GetUpdatesResp"),
			),
			"PlayerMove": Endpoint(
				service_name="DeathOrTaxes",
				name="PlayerMove",
				function=getattr(service, "PlayerMove"),
				input=_sym_db.GetSymbol("PlayerMoveReq"),
				output=_sym_db.GetSymbol("PlayerMoveResp"),
			),
		}

class DeathOrTaxesClient(TwirpClient):

	def GetCollisionMap(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/DeathOrTaxes/GetCollisionMap",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("GetCollisionMapResp"),
			**kwargs,
		)

	def GetUpdates(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/DeathOrTaxes/GetUpdates",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("GetUpdatesResp"),
			**kwargs,
		)

	def PlayerMove(self, *args, ctx, request, server_path_prefix="/twirp", **kwargs):
		return self._make_request(
			url=F"{server_path_prefix}/DeathOrTaxes/PlayerMove",
			ctx=ctx,
			request=request,
			response_obj=_sym_db.GetSymbol("PlayerMoveResp"),
			**kwargs,
		)
