# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: proto/rpc.proto
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='proto/rpc.proto',
  package='',
  syntax='proto3',
  serialized_options=b'Z\005./rpc',
  create_key=_descriptor._internal_create_key,
  serialized_pb=b'\n\x0fproto/rpc.proto\"6\n\x12GetCollisionMapReq\x12 \n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x0b.ClientInfo\"\x84\x01\n\x13GetCollisionMapResp\x12\r\n\x05width\x18\x01 \x01(\x03\x12\x0e\n\x06height\x18\x02 \x01(\x03\x12,\n\x04\x64\x61ta\x18\x03 \x03(\x0e\x32\x1e.GetCollisionMapResp.Collision\" \n\tCollision\x12\t\n\x05\x45MPTY\x10\x00\x12\x08\n\x04WALL\x10\x01\"1\n\rGetUpdatesReq\x12 \n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x0b.ClientInfo\"\x1e\n\x0eGetUpdatesResp\x12\x0c\n\x04word\x18\x01 \x01(\t\"J\n\rPlayerMoveReq\x12 \n\x0b\x63lient_info\x18\x01 \x01(\x0b\x32\x0b.ClientInfo\x12\x17\n\x08position\x18\x02 \x01(\x0b\x32\x05.Vec2\"\x1e\n\x0ePlayerMoveResp\x12\x0c\n\x04word\x18\x01 \x01(\t\"(\n\nClientInfo\x12\x0c\n\x04user\x18\x01 \x01(\t\x12\x0c\n\x04room\x18\x02 \x01(\t\"\x1c\n\x04Vec2\x12\t\n\x01x\x18\x01 \x01(\x03\x12\t\n\x01y\x18\x02 \x01(\x03\x32\xaa\x01\n\x0c\x44\x65\x61thOrTaxes\x12<\n\x0fGetCollisionMap\x12\x13.GetCollisionMapReq\x1a\x14.GetCollisionMapResp\x12-\n\nGetUpdates\x12\x0e.GetUpdatesReq\x1a\x0f.GetUpdatesResp\x12-\n\nPlayerMove\x12\x0e.PlayerMoveReq\x1a\x0f.PlayerMoveRespB\x07Z\x05./rpcb\x06proto3'
)



_GETCOLLISIONMAPRESP_COLLISION = _descriptor.EnumDescriptor(
  name='Collision',
  full_name='GetCollisionMapResp.Collision',
  filename=None,
  file=DESCRIPTOR,
  create_key=_descriptor._internal_create_key,
  values=[
    _descriptor.EnumValueDescriptor(
      name='EMPTY', index=0, number=0,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
    _descriptor.EnumValueDescriptor(
      name='WALL', index=1, number=1,
      serialized_options=None,
      type=None,
      create_key=_descriptor._internal_create_key),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=176,
  serialized_end=208,
)
_sym_db.RegisterEnumDescriptor(_GETCOLLISIONMAPRESP_COLLISION)


_GETCOLLISIONMAPREQ = _descriptor.Descriptor(
  name='GetCollisionMapReq',
  full_name='GetCollisionMapReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_info', full_name='GetCollisionMapReq.client_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=19,
  serialized_end=73,
)


_GETCOLLISIONMAPRESP = _descriptor.Descriptor(
  name='GetCollisionMapResp',
  full_name='GetCollisionMapResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='width', full_name='GetCollisionMapResp.width', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='height', full_name='GetCollisionMapResp.height', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='data', full_name='GetCollisionMapResp.data', index=2,
      number=3, type=14, cpp_type=8, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _GETCOLLISIONMAPRESP_COLLISION,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=76,
  serialized_end=208,
)


_GETUPDATESREQ = _descriptor.Descriptor(
  name='GetUpdatesReq',
  full_name='GetUpdatesReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_info', full_name='GetUpdatesReq.client_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=210,
  serialized_end=259,
)


_GETUPDATESRESP = _descriptor.Descriptor(
  name='GetUpdatesResp',
  full_name='GetUpdatesResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='GetUpdatesResp.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=261,
  serialized_end=291,
)


_PLAYERMOVEREQ = _descriptor.Descriptor(
  name='PlayerMoveReq',
  full_name='PlayerMoveReq',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='client_info', full_name='PlayerMoveReq.client_info', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='position', full_name='PlayerMoveReq.position', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=293,
  serialized_end=367,
)


_PLAYERMOVERESP = _descriptor.Descriptor(
  name='PlayerMoveResp',
  full_name='PlayerMoveResp',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='word', full_name='PlayerMoveResp.word', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=369,
  serialized_end=399,
)


_CLIENTINFO = _descriptor.Descriptor(
  name='ClientInfo',
  full_name='ClientInfo',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='user', full_name='ClientInfo.user', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='room', full_name='ClientInfo.room', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=401,
  serialized_end=441,
)


_VEC2 = _descriptor.Descriptor(
  name='Vec2',
  full_name='Vec2',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  create_key=_descriptor._internal_create_key,
  fields=[
    _descriptor.FieldDescriptor(
      name='x', full_name='Vec2.x', index=0,
      number=1, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
    _descriptor.FieldDescriptor(
      name='y', full_name='Vec2.y', index=1,
      number=2, type=3, cpp_type=2, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR,  create_key=_descriptor._internal_create_key),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=443,
  serialized_end=471,
)

_GETCOLLISIONMAPREQ.fields_by_name['client_info'].message_type = _CLIENTINFO
_GETCOLLISIONMAPRESP.fields_by_name['data'].enum_type = _GETCOLLISIONMAPRESP_COLLISION
_GETCOLLISIONMAPRESP_COLLISION.containing_type = _GETCOLLISIONMAPRESP
_GETUPDATESREQ.fields_by_name['client_info'].message_type = _CLIENTINFO
_PLAYERMOVEREQ.fields_by_name['client_info'].message_type = _CLIENTINFO
_PLAYERMOVEREQ.fields_by_name['position'].message_type = _VEC2
DESCRIPTOR.message_types_by_name['GetCollisionMapReq'] = _GETCOLLISIONMAPREQ
DESCRIPTOR.message_types_by_name['GetCollisionMapResp'] = _GETCOLLISIONMAPRESP
DESCRIPTOR.message_types_by_name['GetUpdatesReq'] = _GETUPDATESREQ
DESCRIPTOR.message_types_by_name['GetUpdatesResp'] = _GETUPDATESRESP
DESCRIPTOR.message_types_by_name['PlayerMoveReq'] = _PLAYERMOVEREQ
DESCRIPTOR.message_types_by_name['PlayerMoveResp'] = _PLAYERMOVERESP
DESCRIPTOR.message_types_by_name['ClientInfo'] = _CLIENTINFO
DESCRIPTOR.message_types_by_name['Vec2'] = _VEC2
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

GetCollisionMapReq = _reflection.GeneratedProtocolMessageType('GetCollisionMapReq', (_message.Message,), {
  'DESCRIPTOR' : _GETCOLLISIONMAPREQ,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:GetCollisionMapReq)
  })
_sym_db.RegisterMessage(GetCollisionMapReq)

GetCollisionMapResp = _reflection.GeneratedProtocolMessageType('GetCollisionMapResp', (_message.Message,), {
  'DESCRIPTOR' : _GETCOLLISIONMAPRESP,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:GetCollisionMapResp)
  })
_sym_db.RegisterMessage(GetCollisionMapResp)

GetUpdatesReq = _reflection.GeneratedProtocolMessageType('GetUpdatesReq', (_message.Message,), {
  'DESCRIPTOR' : _GETUPDATESREQ,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:GetUpdatesReq)
  })
_sym_db.RegisterMessage(GetUpdatesReq)

GetUpdatesResp = _reflection.GeneratedProtocolMessageType('GetUpdatesResp', (_message.Message,), {
  'DESCRIPTOR' : _GETUPDATESRESP,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:GetUpdatesResp)
  })
_sym_db.RegisterMessage(GetUpdatesResp)

PlayerMoveReq = _reflection.GeneratedProtocolMessageType('PlayerMoveReq', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERMOVEREQ,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:PlayerMoveReq)
  })
_sym_db.RegisterMessage(PlayerMoveReq)

PlayerMoveResp = _reflection.GeneratedProtocolMessageType('PlayerMoveResp', (_message.Message,), {
  'DESCRIPTOR' : _PLAYERMOVERESP,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:PlayerMoveResp)
  })
_sym_db.RegisterMessage(PlayerMoveResp)

ClientInfo = _reflection.GeneratedProtocolMessageType('ClientInfo', (_message.Message,), {
  'DESCRIPTOR' : _CLIENTINFO,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:ClientInfo)
  })
_sym_db.RegisterMessage(ClientInfo)

Vec2 = _reflection.GeneratedProtocolMessageType('Vec2', (_message.Message,), {
  'DESCRIPTOR' : _VEC2,
  '__module__' : 'proto.rpc_pb2'
  # @@protoc_insertion_point(class_scope:Vec2)
  })
_sym_db.RegisterMessage(Vec2)


DESCRIPTOR._options = None

_DEATHORTAXES = _descriptor.ServiceDescriptor(
  name='DeathOrTaxes',
  full_name='DeathOrTaxes',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  create_key=_descriptor._internal_create_key,
  serialized_start=474,
  serialized_end=644,
  methods=[
  _descriptor.MethodDescriptor(
    name='GetCollisionMap',
    full_name='DeathOrTaxes.GetCollisionMap',
    index=0,
    containing_service=None,
    input_type=_GETCOLLISIONMAPREQ,
    output_type=_GETCOLLISIONMAPRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='GetUpdates',
    full_name='DeathOrTaxes.GetUpdates',
    index=1,
    containing_service=None,
    input_type=_GETUPDATESREQ,
    output_type=_GETUPDATESRESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
  _descriptor.MethodDescriptor(
    name='PlayerMove',
    full_name='DeathOrTaxes.PlayerMove',
    index=2,
    containing_service=None,
    input_type=_PLAYERMOVEREQ,
    output_type=_PLAYERMOVERESP,
    serialized_options=None,
    create_key=_descriptor._internal_create_key,
  ),
])
_sym_db.RegisterServiceDescriptor(_DEATHORTAXES)

DESCRIPTOR.services_by_name['DeathOrTaxes'] = _DEATHORTAXES

# @@protoc_insertion_point(module_scope)
